### PR TITLE
Add extension (openDate)

### PR DESCRIPTION
**Pull request by dickymuliafiqri**
This extension will prevent someone open this page too early or too late, using UTC time date.

How it's work ?
Just redirect main page to target page when condition is true.

### CODE REVIEW

**Comment by AnshumanMahato** [comment]
Hey, Thanks for your contribution ❤...
The feature looks good. I'll get back to you after testing, if it requires any changes...

**Comment by AnshumanMahato** [comment]
Can you tell me what is FUNDING.yml for?

**Comment by dickymuliafiqri** [comment]
> Can you tell me what is FUNDING.yml for?

No no no, that's a mess.
You can delete that file.

Also, i already made another changes about the extension, waiting this commit to be merged then i'll make another PR.

**Comment by dickymuliafiqri** [comment]
I know, but unfortunately i have no access to my pc for now. I'll update this pr asap.

**Comment by AnshumanMahato** [comment]
No problem. I'll wait until then.😊

**Pull request merged**
